name: local_user
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  local_value: ^1.1.1
  uuid_type:
    path: ../uuid_type
  flutter:
    sdk: flutter
    version: ^0.0.0
