#These docker-composes are for development purposes only;
#deployment is done through pulumi.
version: "3.8"

x-environment:
    &default-environment
    POSTGRES_USER: &pg_user vscode
    POSTGRES_PASSWORD: &pg_pass notsecure
    POSTGRES_DB: mydb
    POSTGRES_HOST: &pg_host db
    POSTGRES_PORT: &pg_port 5432
    JWT_SECRET: IMSECRETDONTLOOKATME
    USER_SECRET: usersecret
    ADMIN_SECRET: adminsecret
services:
    db:
        container_name: *pg_host
        image: gradescope/postgresql-multiple-databases:14.2
        restart: always
        environment:
            POSTGRES_MULTIPLE_DATABASES: mydb,shadow_mydb
            POSTGRES_USER: *pg_user
            POSTGRES_PASSWORD: notsecure
            POSTGRES_HOST: *pg_host
            POSTGRES_PORT: *pg_port
        ports:
            - 5433:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
    postgraphile:
        build: ./postgraphile
        ports:
            - 8080:8080
            - 9231:9229
        volumes:
            - ./postgraphile:/usr/src/app
            - postgraphile_modules:/user/src/app/node_modules
            - ./mobile/lib/schema.graphql:/schema.graphql
        environment: *default-environment
volumes:
  pg_data:
  postgraphile_modules:
