#These docker-composes are for development purposes only;
#deployment is done through pulumi.
version: "3.8"

services:
    db:
        container_name: ${POSTGRES_HOST}
        image: gradescope/postgresql-multiple-databases:14.2
        restart: always
        environment:
            POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB},shadow_${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        ports:
            - 5433:${POSTGRES_PORT}
        volumes:
            - pg_data:/var/lib/postgresql/data
    postgraphile:
        build: ./postgraphile
        ports:
            - 8080:8080
            - 9231:9229
        volumes:
            - ./postgraphile:/usr/src/app
            - postgraphile_modules:/user/src/app/node_modules
            - ./mobile/lib/schema.graphql:/schema.graphql
        env_file:
            - .env
volumes:
  pg_data:
  postgraphile_modules:
