version: '3.8'
services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:14
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
        - 5433:${POSTGRES_PORT}
  actix:
    build: fns
    ports:
     - 3000:3000
    volumes:
    - ./fns:/usr/src/app
    environment:
        WEBHOOK_SECRET_KEY: '${WEBHOOK_SECRET_KEY}'
        ADMIN_LOGIN_SECRET: '${ADMIN_LOGIN_SECRET}'
        USER_LOGIN_SECRET: '${USER_LOGIN_SECRET}'
        HASURA_ENDPOINT: '${HASURA_ENDPOINT}'
        HASURA_ADMIN_SECRET: '${ADMIN_SECRET}'
        JWT_SECRET: '${JWT_SECRET}'
    command: cargo watch -x run
  hasura:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    ports:
    - 8080:8080
    depends_on:
    - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: '${ADMIN_SECRET}'
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256","key": "${JWT_SECRET}"}'
      WEBHOOK_URL: '${WEBHOOK_URL}'
      WEBHOOK_SECRET_KEY: '${WEBHOOK_SECRET_KEY}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'unauthenticated'
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
volumes:
  db_data: