targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            uuid:
              type: UuidType
              fromJsonFunctionName: uuidTypeFromJson
              toJsonFunctionName: uuidTypeToJson
              import: package:uuid_type/uuid_type.dart
            JwtToken:
              type: String
