targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            uuid:
              type: UuidType
              fromJsonFunctionName: UuidType.fromJson
              toJsonFunctionName: UuidType.toJson
              import: package:uuid_type/uuid_type.dart
