name: gametime
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  auto_route: ^4.0.0
  flutter_bloc: ^8.0.1
  toaster_next: ^1.1.0

  uuid_type:
    path: ./stdlib/uuid_type
  gql_client:
    path: ./stdlib/gql_client

  # for json conversion
  date_time_converter:
    path: ./stdlib/date_time_converter
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.4
  auto_route_generator: ^4.0.0
  freezed: ^2.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/provider_logos/