-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "private"."users" add column "admin" boolean
--  not null default 'false';
