name: gql_client
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  local_value: ^1.1.1
  graphql: ^5.0.0

  local_user:
    path: ../local_user
  uuid_type:
    path: ../uuid_type

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
